language: node_js
node_js:
  - "8"

#addons:
#    code_climate:
#        repo_token:

install:
  - npm install

script:
  - npm run build

# Send coverage data to Coveralls
#after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: c502c5e00dd9e21905f9f967c20b9567beb8c42e
  on:
    branch: master
  local_dir: dist