language: node_js

node_js:
  - "8"

install:
  - npm install
#  - npm install -g webpack@3.10.0
#  - npm install -g babel-loader@7.1.2
#  - npm install -g css-loader@0.28.7
#  - npm install -g eslint-loader@1.9.0
#  - npm install -g handlebars-loader@1.6.0
#  - npm install -g required-loader@1.3.16
#  - npm install -g sass-loader@6.0.6
#  - npm install -g style-loader@0.19.0
#  - npm install -g json-loader@0.5.7
#  - npm install -g webpack-dev-server@2.9.7
#  - npm install -g webpack-merge@4.1.1
#  - npm install -g clean-webpack-plugin@0.1.17
#  - npm install -g html-webpack-plugin@2.30.1
#  - npm install -g extract-text-webpack-plugin@3.0.2
#  - npm install -g babel-eslint@8.0.3
#  - npm install -g babel-plugin-resolver@1.1.0
#  - npm install -g node-sass@4.7.2
#  - npm install -g babel-core@6.26.0
#  - npm install -g babel-preset-es2015@6.24.1
#  - npm install -g eslint@4.13.0

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm run test
  - npm run build

# Here we want to check out where we are.
# We only want to update Github Pages if we're building
# the master branch of the original repository, so we
# have to check $TRAVIS_PULL_REQUEST and $TRAVIS_BRANCH.
# If we are here, we run bash deploy.sh
after_success:
 - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash deploy.sh

#deploy:
#  provider: pages
#  skip_cleanup: true
#  github_token: pzvNyrsmnHqb418x32fs
#  on:
#    branch: master

env:
  global:
    - GITHUB_REPO: "proustibat/demo-rellax"
    - secure: "tCRSfERQWucjcCxyJ7JcSIFvBYtyFF3AHqmW6qRM5oamyuCsQiuip79fh9oYV6UDv91XmtTJWusubFaaFJjRGLVgFMgYMCRCZ35CgJbpPTiGOxV0vuEd986OYp3N03eGKqxdgyFGxckRdnuHEtZaSM02cDt5En55ixBp89sHMvJpZE5IIuFf1ypgdZHhEteHMsJn3DnILvNnDeLgpvKUPyejSUCrAGmWOU638IzjKK2R9MKuCEID/HeuE/RSrA2oR9IuHL3ww+Qr6zr3pvp4WmRFg6jZ3X6vB2pYkgXT2I2x1IhwuRnb2mCNPIU194VquceLXn/deOtlzYMHul56po0h2FEouHVJESGSpZ/NUIhpj91GvTrVbNZNz/lcK8uqHCn04h8BJ4K6ai52R3ni7Ajuy254p1qFScX8Vhwzfw3errJNJbYm4A+HXnbw4oiBdZlNHjPjhFp3dzPvNNoaDwj0rNAL7txn3FekP4zDYNeFt2F+x9EQkEL/MUWs7qK8j0fD2aJ7RUJsraj9ZanJ/vH6alqYLuJkeuQYbVuzAwqEwbQl68QgSruk2ikHg72zPxOCoh2owQubEFFgIAYQi9sFMShrn1xANe+UZu3oyATz6iaf0ilpAfRbIoN8QnLov3i+RWrpFtXDLqMBMEBVegfePJwO+qMJ02Vnm7qbnlg="
