language: node_js
node_js:
  - "8"

#addons:
#    code_climate:
#        repo_token:

install:
  - npm install

script:
  - npm run build

# Send coverage data to Coveralls
#after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: 958720e49489309a4ff976a8411315ead877ba3d
  on:
    branch: master
  local_dir: dist